version: '3.8'

services:
  api:
    build: .
    command: python /football-squad/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/football-squad
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:11
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"